---
- hosts: localhost
  gather_facts: false

  pre_tasks:
    - name: Set the required variables
      set_fact:
        ingest_token: "{{ lookup('env','ACCESS_TOKEN') }}"
        rum_token: "{{ lookup('env','RUM_TOKEN') }}"
        realm: "{{ lookup('env','REALM') }}"
        instance: "{{ lookup('env','INSTANCE') }}"
        hec_url: "{{ lookup('env','HEC_URL') }}"
        hec_token: "{{ lookup('env','HEC_TOKEN') }}"

  tasks:
    - name: Configure Demo-in-a-Box
      block:
      - name: Check to see if the config has run
        stat:
          path: /white_rabbit.followed
        register: wh_result

      - name: Extract demo-in-a-box into /home/splunk/
        unarchive:
          src: demo-in-a-box.zip
          dest: /home/splunk/
          owner: splunk
          group: splunk
          remote_src: yes
          list_files: yes
        become: true
        register: diab_dir_name
        when: not wh_result.stat.exists

      #- name: Delete demo-in-a-box.zip
      #  file:
      #    path: /home/splunk/demo-in-a-box.zip
      #    state: absent
      #  become: true
      #  when: not wh_result.stat.exists
        
      - debug:
          var: diab_dir_name.files[0]
        when: not wh_result.stat.exists

      - name: Create workshop secrets deployment deployment.yaml
        file:
          path: /home/splunk/workshop-secrets.yaml
          owner: splunk
          group: splunk
          state: touch
        become: true
        when: not wh_result.stat.exists

      - name: Update yaml for workshop secrets
        ansible.builtin.blockinfile:
          path: /home/splunk/workshop-secrets.yaml
          block: |
            apiVersion: v1
            kind: Secret
            metadata:
              name: workshop-secret
              namespace: default
            type: Opaque
            stringData:
              frontend-app: {{ instance }}-frontend-store
              profiling-app: {{ instance }}-profiling-store
              astronomy-app: {{ instance }}-astronomy-store
              deployment: "deployment.environment={{ instance }}-diab"
              access_token: {{ ingest_token }}
              api_token: {{ ingest_token }}
              realm: {{ realm }}
              rum_token: {{ rum_token }}
              hec_url: {{ hec_url }}
              hec_token: {{ hec_token }}
          marker: "## {mark} added by ansible (configuration demo-in-a-box)"
        become: true
        when: not wh_result.stat.exists

      - name: Install secrets
        command: kubectl apply -f workshop-secrets.yaml
        when: not wh_result.stat.exists

      - name: Create service for Demo-in-a-Box
        file:
          path: /etc/systemd/system/demoinabox.service
          state: touch
        become: true
        when: not wh_result.stat.exists

      - name: Update service for demoinabox.service
        ansible.builtin.blockinfile:
          path: /etc/systemd/system/demoinabox.service
          block: |
            [Unit]
            Description=demoinabox service
            After=network.target
            StartLimitIntervalSec=0
            [Service]
            Type=simple
            Restart=always
            RestartSec=1
            User=splunk
            Environment="KUBECONFIG=/home/splunk/.kube/config"
            WorkingDirectory=/home/splunk/{{ diab_dir_name.files[0] }}manager
            ExecStart=/bin/bash run-manager.sh
            [Install]
            WantedBy=multi-user.target
          marker: "## {mark} added by ansible (configuration demo-in-a-box)"
        become: true
        when: not wh_result.stat.exists

      #- name: Install democonsole Python dependencies
      #  command: python3 -m pip install -r requirements.txt --upgrade
      #  args:
      #    chdir: "/home/splunk/{{ diab_dir_name.files[0] }}manager/"
      #  when: not wh_result.stat.exists

      - name: Helm OTel Collector repository add
        command: helm repo add splunk-otel-collector-chart https://signalfx.github.io/splunk-otel-collector-chart
        when: not wh_result.stat.exists

      - name: Helm repository update
        command: helm repo update
        when: not wh_result.stat.exists

      - name: Start the demoinabox service
        command: systemctl enable --now demoinabox.service
        become: true
        when: not wh_result.stat.exists

      - name: Wait for demoinabox.service to start
        pause:
          seconds: 20
        when: not wh_result.stat.exists

      - name: Save Demo-in-a-Box configuration
        uri:
          url: "http://localhost:8081/saveConfig"
          method: POST
          body: "realm={{ realm }}&ingest_token={{ ingest_token }}&rum_token={{ rum_token }}&instance={{ instance }}"
          status_code: [ 200, 201 ]
          timeout: 30
        when: not wh_result.stat.exists

      - name: Start the OpenTelemetry Collector
        uri:
          url: "http://localhost:8081/startCollector"
          method: GET
          status_code: [ 200, 201 ]
          timeout: 30
        when: not wh_result.stat.exists

      - name: Wait for OpenTelemetry Collector to start
        pause:
          seconds: 30
        when: not wh_result.stat.exists

      - name: Start the frontend demo
        uri:
          url: "http://localhost:8081/startdemo?demo=frontend"
          method: GET
          status_code: [ 200, 201 ]
          timeout: 30
        when: not wh_result.stat.exists

      - name: Wait for frontend demo to start
        pause:
          seconds: 30
        when: not wh_result.stat.exists

      - name: Wait for the Online Boutique to become available
        uri:
          url: "http://localhost:81"
          method: GET
          validate_certs: no
          status_code: 200
          return_content: no
        register: splunk_ui
        until: splunk_ui.status == 200
        retries: 30
        delay: 5

      - name: Create a file to signify that the config has run successfully
        file:
          path: "/white_rabbit.followed"
          state: touch
        become: true
        when: not wh_result.stat.exists
