# ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-contrib-configmap
data:
  splunk_otlp_trace_url: "http://192.168.5.158:4318/v1/traces"
  splunk_otlp_metric_url: "http://192.168.5.158:4318/v1/metrics"
  splunk_otlp_log_url: "http://192.168.5.158:4318/v1/logs"
  splunk_api_url: "http://192.168.5.158:6060"
  splunk_ingest_url: "http://192.168.5.158:9943"
  k8s_cluster_name: "otel-contrib-cluster-v2"
  deployment_environment: "otel-contrib-v2"
---
# Secrets
apiVersion: v1
kind: Secret
metadata:
  name: otel-contrib-collector
  namespace: default
  labels:
    app.kubernetes.io/name: otel-collector
    app: otel-collector
type: Opaque
stringData:
  splunk_observability_access_token: <redacted>
