baseURL: https://signalfx.github.io/
title: Splunk Observability Cloud Workshops
contentDir: content/en
defaultContentLanguage: en
defaultContentLanguageInSubdir: false
enableMissingTranslationPlaceholders: true
enableRobotsTXT: true
theme:
  - docsy
enableGitInfo: true
taxonomies:
  tag: tags
  category: categories
params:
  taxonomy:
    taxonomyCloud:
      - tags
      - categories
    taxonomyCloudTitle:
      - Tag Cloud
      - Categories
    taxonomyPageHeader:
      - tags
      - categories
    pygmentsCodeFences: true
    pygmentsUseClasses: false
    pygmentsUseClassic: false
    pygmentsStyle: tango
  copyright: Splunk Inc.
  privacy_policy: ''
  archived_version: false
  version_menu: Releases
  versions:
    - version: latest
      url: https://signalfx.github.io/observability-workshop/latest/
    - version: v4.31
      url: https://signalfx.github.io/observability-workshop/v4.31
    - version: v4.32
      url: https://signalfx.github.io/observability-workshop/v4.32
  url_latest_version: https://signalfx.github.io/observability-workshop/
  #github_repo: https://github.com/signalfx/observability-workshop
  #github_project_repo: https://github.com/signalfx/observability-workshop
  #gcs_engine_id: d72aa9b2712488cc3
  workshop_menu: More Workshops
  workshop_menu_urls:
    - name: Pet Clinic Java Workshop
      url: https://signalfx.github.io/observability-workshop/latest/pet-clinic/
    - name: O11y Bootcamp
      url: https://signalfx.github.io/observability-workshop/latest/bootcamp/
    - name: Resources
      url: https://signalfx.github.io/observability-workshop/latest/resources/
  algolia_docsearch: false
  offlineSearch: true
  ui:
    breadcrumb_disable: false
    footer_about_disable: false
    navbar_logo: true
    navbar_translucent_over_cover_disable: false
    sidebar_menu_compact: false
    sidebar_search_disable: false
    sidebar_menu_foldable: false
    readingtime:
      enable: true
  links:
    developer:
      - name: "GitHub"
        url: "https://github.com/signalfx/observability-workshop"
        icon: "fab fa-github"
    user:
      - name: Twitter
        url: 'https://twitter.com/splunk'
        icon: fab fa-twitter
        desc: Follow us on Twitter to get the latest news!
permalinks:
  blog: '/:section/:year/:month/:day/:slug/'
imaging:
  resampleFilter: CatmullRom
  quality: 75
  anchor: smart
languages:
  en:
    title: 'Splunk Observability Cloud Workshops'
    description: Splunk Observability Workshops
    languageName: English
    weight: 1
  ja:
    title: 'Splunk Observability Cloud Workshops'
    description: Splunk Observability ワークショップ
    languageName: 日本語
    contentDir: content/ja
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: tango
outputs:
  section:
    - HTML
    #    - print
    - RSS
