baseURL: https://splunk.github.io/
canonifyURLs: true
relativeURLs: true
title: Splunk Observability Cloud Workshops
contentDir: content/en
defaultContentLanguage: en
defaultContentLanguageInSubdir: false
enableMissingTranslationPlaceholders: true
enableRobotsTXT: true
module:
  imports:
    - path: github.com/McShelby/hugo-theme-relearn
theme:
  - github.com/McShelby/hugo-theme-relearn
languages:
  en:
    title: 'Splunk Observability Cloud Workshops'
    description: Splunk Observability Workshops
    languageName: English
    weight: 1
  ja:
    title: 'Splunk Observability Cloud Workshops'
    description: Splunk Observability ワークショップ
    contentDir: content/ja
    languageName: 日本語
    weight: 2
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: tango
outputs:
  home:
    - HTML
    - RSS
    - PRINT
    - SEARCH
    - SEARCHPAGE
  section:
    - HTML
    - RSS
    - PRINT
  page:
    - HTML
    - RSS
    - PRINT
params:
  alwaysopen: false
  description: "Splunk Observability Workshops"
  showVisitedLinks: true
  collapsibleMenu: true
  disableSearch: false
  disableBreadcrumb: false
  disableInlineCopyToClipBoard: true
  disableNextPrev: false
  disableLandingPageButton: false
  titleSeparator: "::"
  themeVariant: ["splunk-light", "splunk-dark", "aws"]
  additionalContentLanguage: ["ja"]
  versions:
    - version: latest
      url: https://splunk.github.io/observability-workshop/latest/
    - version: v4.63
      url: https://splunk.github.io/observability-workshop/v4.63
    - version: v4.64
      url: https://splunk.github.io/observability-workshop/v4.64
  url_latest_version: https://splunk.github.io/observability-workshop/
menu:
  shortcuts:
    - name: "<i class='fab fa-fw fa-github'></i> GitHub Repository"
      url: "https://github.com/splunk/observability-workshop"
      weight: 10
    - name: <i class="fab fa-fw fa-wpexplorer"></i> OpenTelemetry
      url: "https://opentelemetry.io"
      weight: 20
    - name: <i class="fab fa-fw fa-twitter"></i> Twitter
      url: "https://twitter.com/splunk"
      weight: 30
