baseURL: https://rcastley.github.io/
title: ''
contentDir: content/en
defaultContentLanguage: en
defaultContentLanguageInSubdir: false
enableMissingTranslationPlaceholders: true
enableRobotsTXT: true
theme:
  - docsy
enableGitInfo: true
relativeURLs: true
params:
  taxonomy:
    pygmentsCodeFences: true
    pygmentsUseClasses: false
    pygmentsUseClassic: false
    pygmentsStyle: tango
  copyright: Splunk Inc.
  privacy_policy: ''
  version_menu: Releases
  versions:
    - version: latest
      url: 'https://rcastley.github.io/observability-workshop/v3.33/'
    - version: v3.14
      url: 'https://signalfx.github.io/observability-workshop/v3.14/'
    - version: v3.12
      url: 'https://signalfx.github.io/observability-workshop/v3.12/'
  url_latest_version: 'https://signalfx.github.io/observability-workshop/'
  github_repo: 'https://github.com/signalfx/observability-workshop'
  github_project_repo: 'https://github.com/signalfx/observability-workshop'
  ui:
    breadcrumb_disable: false
    footer_about_disable: false
    navbar_logo: true
    navbar_translucent_over_cover_disable: false
    sidebar_menu_compact: true
    sidebar_search_disable: false
    sidebar_menu_foldable: true
    readingtime:
      enable: true
  links:
    developer:
      - name: "GitHub"
        url: "https://github.com/signalfx/observability-workshop"
        icon: "fab fa-github"
    user:
      - name: Twitter
        url: 'https://twitter.com/splunk'
        icon: fab fa-twitter
        desc: Follow us on Twitter to get the latest news!
permalinks:
  blog: '/:section/:year/:month/:day/:slug/'
imaging:
  resampleFilter: CatmullRom
  quality: 75
  anchor: smart
languages:
  en:
    title: ''
    description: Splunk Observability Workshops
    languageName: English
    weight: 1
  ja:
    title: ''
    description: Splunk の観察力ワークショップ
    languageName: 日本語
    weight: 2
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: tango
outputs:
  section:
    - HTML
    - print
    - RSS
menu:
  main:
    - name: Splunk IMT
      url: imt/
      weight: 10
    - name: Splunk APM
      url: apm/
      weight: 20
    - name: Splunk RUM
      url: rum/
      weight: 30
    - name: Splunk Synthetics
      url: synthetics/
      weight: 40
    - name: Observability Bootcamp
      url: bootcamp/
      weight: 50
