site_name: Splunk Observability Cloud Workshop
site_url: https://signalfx.github.io/observability-workshop/
site_author: Sales Engineering EMEA
site_description: >-
  This workshop is going to take you through the best-in-class observability platform
  for ingesting, monitoring, visualizing and analyzing metrics, traces and spans

repo_url: https://github.com/signalfx/observability-workshop/
edit_uri: ""
copyright: Copyright &copy; 2021 Splunk Inc. All rights reserved.
remote_branch: gh-pages

theme:
  name: material
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  favicon: images/favicon.ico
  logo: images/logo.png
  font:
    text: Roboto
    code: Roboto Mono
  include_search_page: false
  search_index_only: true
  language: en
  custom_dir: material
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - navigation.top
    - toc.integrate

markdown_extensions:
  - footnotes
  - admonition
  - attr_list
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.critic
  - pymdownx.keys
  - meta
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: true

extra_css:
  - "stylesheets/extra.css"

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/signalfx/observability-workshop
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/splunk
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/splunk/
  version: 2.13

plugins:
  - search
  - git-revision-date-localized:
      type: timeago
  - minify:
      minify_html: true

nav:
  - Home: index.md
  - Splunk IMT:
    - Workshop Introduction: otel/index.md
    - Initial Setup<br /><small>5 minutes</small>:
      - Access AWS/EC2 instance: otel/connect-info.md 
    - Get Data In<br /><small>20 minutes</small>:
      - Deploy the OTel Collector: otel/k3s.md
      - Deploy and monitor NGINX : otel/nginx.md
    - Dashboards<br /><small>30 minutes</small>:
      - Introduction: dashboards/index.md
      - Editing charts: dashboards/editing.md
      - Saving charts: dashboards/savingcharts.md
      - Using filters & formulas: dashboards/filtering.md
      - SignalFlow: dashboards/signalflow.md
      - Adding more charts: dashboards/adding-charts.md
      - Notes and layout: dashboards/dashboarding.md
    - Detectors<br /><small>15 minutes</small>:
      - Creating a Detector: detectors/index.md
      - Creating a Muting Rule: detectors/muting.md
    - Monitoring as Code<br /><small>10 minutes</small>:
      - Plan, Apply and Destroy: monitoring-as-code/index.md
  - Splunk APM:
    - Introduction: apm/index.md
    - Get Traces In<br /><small>15 minutes</small>:
      - Deploying the Online Boutique: apm/online-boutique.md
    - Troubleshooting APM<br /><small>15 minutes</small>:
      - TBD: apm/using-apm.md
  - Service Bureau:
    - Billing and Usage : servicebureau/billing-and-usage.md
    - Teams : servicebureau/teams.md
    - Control Usage: servicebureau/tokens.md
  - Splunk On-Call:
    - Getting Started<br /><small>45 minutes</small>:
      - Initial Setup: oncall/getting_started/index.md
      - User Profile: oncall/getting_started/user_profile.md
      - Teams: oncall/getting_started/team.md
      - Configure Rotations: oncall/getting_started/rotations.md
      - Configure Escalation Policies: oncall/getting_started/escalation.md
      - Creating Routing keys: oncall/getting_started/routing.md
    - Incident Lifecycle<br /><small>45 minutes</small>:
      - Overview: oncall/incident_lifecycle/index.md
      - Create Incidents: oncall/incident_lifecycle/create_incidents.md
      - Manage Incidents: oncall/incident_lifecycle/manage_incidents.md
    - Optional Modules:
      - Observability Cloud Integration: oncall/optional/sfx_integrations.md
      - Using Multipass VM: oncall/optional/multipass.md
      - Create a Detector: oncall/optional/detector.md
  #- Lambda & APM:
  #  - Intro: lambda/index.md
  #  - Getting to know the Mobile Shop: lambda/initial_run_env.md
  #  - APM for Mobile Shop:
  #    - Setting up Springboot App : lambda/springboot-apm.md 
  #    - Getting the first Trace: lambda/springboot-apm-II.md
  #  - APM for RetailOrder:
  #    - Basic Instrumentation: lambda/retail-order-I.md
  #  - APM for RetailOrderPrice:
  #    - Work in progress: lambda/wip.md
  #  - APM for RetailOrderDiscount: 
  #    - Work in progress: lambda/wip.md
  #  - APM for RetailOrderLine:
  #    - Basic Instrumentation: lambda/retail-orderline-I.md
  #  - Setup: lambda/setup.md
  - Resources:
    - Links: resources/index.md
    - FAQ: resources/faq.md

