site_name: Splunk Observability Cloud Workshops
site_url: https://signalfx.github.io/observability-workshop/
site_author: Sales Engineering EMEA
site_description: >-
  This workshop is going to take you through the best-in-class observability platform
  for ingesting, monitoring, visualizing and analyzing metrics, traces and spans

repo_name: signalfx/observability-workshop
repo_url: https://github.com/signalfx/observability-workshop/
edit_uri: ""
copyright: Copyright &copy; 2022 Splunk Inc. All rights reserved.
remote_branch: gh-pages

theme:
  name: material
  custom_dir: !ENV [THEME_DIR, "overrides"]
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  favicon: images/favicon.ico
  logo: images/logo.png
  font:
    text: "Century Gothic"
    code: Roboto Mono
  include_search_page: false
  search_index_only: true
  language: en
  features:
    - content.code.annotate
    - navigation.indexes
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - toc.integrate

markdown_extensions:
  - footnotes
  - admonition
  - attr_list
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.critic
  - pymdownx.keys
  - meta
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: true

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/signalfx/observability-workshop
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/splunk
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/splunk/
  version:
    provider: mike
  alternate:
    # Switch to English
    - name: English
      link: ./en/
      lang: en
    # Switch to Japanese
    - name: 日本語
      link: ./ja/
      lang: ja

plugins:
  - git-revision-date-localized:
      type: date
  - i18n:
      default_language: en
      languages:
        en: English
        ja: 日本語
      nav_translations:
        ja:
          Workshop Introduction: ワークショップの概要
          Initial Setup<br /><small>5 minutes</small>: 初期セットアップ<br /><small>5分</small>
          Access AWS/EC2 instance: AWS/EC2インスタンスに接続する
          Get Data In<br /><small>15 minutes</small>: データを取り込む<br /><small>15分</small>
          Deploy the OTel Collector: OTel Collectorをデプロイする
          Deploy and monitor NGINX : NGINXをデプロイしてモニタリングする
          Dashboards<br /><small>20 minutes</small>: ダッシュボード<br /><small>20分</small>
          Introduction: はじめに
          Editing charts: チャートを編集する
          Saving charts: チャートを保存する
          Using filters & formulas: フィルターと数式を使用する
          SignalFlow: SignalFlow
          Adding more charts: チャートを追加する
          Notes and layout: ノートの追加とレイアウト
          Detectors<br /><small>10 minutes</small>: ディテクター<br /><small>10分</small>
          Creating a Detector: ディテクターを作成する
          Creating a Muting Rule: ミューティングルールを作成する
          Monitoring as Code<br /><small>10 minutes</small>: Monitoring as Code<br /><small>10分</small>
          Plan, Apply and Destroy: Plan, Apply, Destroy
          Service Bureau<br /><small>10 minutes</small>: サービスビューロー<br /><small>10分</small>
          Billing and Usage : 使用量と料金の管理
          Teams : チームの管理
          Control Usage: 使用量を制御する
          Introduction: はじめに
          Get Traces In<br /><small>10 minutes</small>: トレースを取り込む<br /><small>10 minutes</small>
          Deploying the Online Boutique: Online Boutiqueをデプロイする
          Get Data Out<br /><small>15 minutes</small>: データを取り出す<br /><small>15 minutes</small>
          Using Splunk APM: Splunk APMを使ってみる

nav:
  - Home: index.md
  - Splunk IMT:
    - Workshop Introduction: otel/intro.md
    - User Interface Overview: otel/ui.md
    - Initial Setup<br /><small>5 minutes</small>:
      - Access AWS/EC2 instance: otel/connect-info.md
    - Get Data In<br /><small>15 minutes</small>:
      - Deploy the OTel Collector: otel/k3s.md
      - Deploy and monitor NGINX : otel/nginx.md
    - Dashboards<br /><small>20 minutes</small>:
      - Introduction: dashboards/intro.md
      - Editing charts: dashboards/editing.md
      - Saving charts: dashboards/savingcharts.md
      - Using filters & formulas: dashboards/filtering.md
      - SignalFlow: dashboards/signalflow.md
      - Adding more charts: dashboards/adding-charts.md
      - Notes and layout: dashboards/dashboarding.md
    - Detectors<br /><small>10 minutes</small>:
      - Creating a Detector: detectors/intro.md
      - Creating a Muting Rule: detectors/muting.md
    - Monitoring as Code<br><small>10 minutes</small>:
      - Plan, Apply and Destroy: monitoring-as-code/terraform.md
    - Service Bureau<br /><small>10 minutes</small>:
      - Billing and Usage : servicebureau/billing-and-usage.md
      - Teams : servicebureau/teams.md
      - Control Usage: servicebureau/tokens.md
  - Splunk APM:
    - APM, an introduction: apm/index.md
    - Get Traces In<br /><small>10 minutes</small>:
      - Deploying the Online Boutique: apm/online-boutique.md
    - Get Data Out<br /><small>15 minutes</small>:
      - Using Splunk APM: apm/using-apm.md
  - Splunk RUM:
    - RUM, an introduction: rum/intro.md
    - Using RUM on your Website: rum/RUM-Setup.md
    - RUM Showcase: rum/RUM-online-boutique.md
    - Analyzing RUM Metrics: rum/RUM-Metrics.md
    - Using Tag Spotlight: rum/RUM-Tag.md
    - Discovering RUM sessions: rum/RUM-Sessions.md
    - Correlation of RUM & APM: rum/RUM-APM.md
  - Splunk Synthetics:
    - Real Browser Checks<br /><small>40 minutes</small>:
      - Synthetics, an introduction: synthetics/intro.md
    - API Checks<br /><small>20 minutes</small>:
      - Introduction: synthetics/api.md
#  - Splunk On-Call:
#    - Getting Started<br /><small>45 minutes</small>:
#      - On-Call, the initial Setup: oncall/getting_started/index.md
#      - User Profile: oncall/getting_started/user_profile.md
#      - Teams: oncall/getting_started/team.md
#      - Configure Rotations: oncall/getting_started/rotations.md
#      - Configure Escalation Policies: oncall/getting_started/escalation.md
#      - Creating Routing keys: oncall/getting_started/routing.md
#    - Incident Lifecycle<br /><small>45 minutes</small>:
#      - Overview: oncall/incident_lifecycle/index.md
#      - Create Incidents: oncall/incident_lifecycle/create_incidents.md
#      - Manage Incidents: oncall/incident_lifecycle/manage_incidents.md
#    - Optional Modules:
#      - Observability Cloud Integration: oncall/optional/sfx_integrations.md
#      - Using Multipass VM: oncall/optional/multipass.md
#      - Create a Detector: oncall/optional/detector.md
#- Lambda & APM:
#  - Intro: lambda/index.md
#  - Getting to know the Mobile Shop: lambda/initial_run_env.md
#  - APM for Mobile Shop:
#    - Setting up Springboot App : lambda/springboot-apm.md
#    - Getting the first Trace: lambda/springboot-apm-II.md
#  - APM for RetailOrder:
#    - Basic Instrumentation: lambda/retail-order-I.md
#  - APM for RetailOrderPrice:
#    - Work in progress: lambda/wip.md
#  - APM for RetailOrderDiscount:
#    - Work in progress: lambda/wip.md
#  - APM for RetailOrderLine:
#    - Basic Instrumentation: lambda/retail-orderline-I.md
#  - Setup: lambda/setup.md
  - Observability Bootcamp:
    - Introduction: bootcamp/index.md
    - OpenTelemetry & Get Data In:
      - Introduction: bootcamp/gdi/lab-otel-gdi.md
      - Create a monolith Service: bootcamp/gdi/monolith.md
      - Add Prometheus metrics: bootcamp/gdi/prometheus.md
      - Deploy OpenTelemetry Collector in Docker: bootcamp/gdi/otel.md
      - Capture Prometheus metrics: bootcamp/gdi/otel-prometheus.md
      - Dockerize the Service: bootcamp/gdi/docker.md
      - Container orchestration: bootcamp/gdi/docker-compose.md
      - Deploy OpenTelemetry in Docker Compose: bootcamp/gdi/otel-docker-compose.md
      - Monitor containerized services: bootcamp/gdi/otel-container-svc.md
      - Kubernetes: bootcamp/gdi/k8s.md
    - Microservices APM:
      - Introduction: bootcamp/apm/lab-otel-apm.md
      - Microservices auto-instrumentation: bootcamp/apm/autoi.md
      - Instrumentation in Kubernetes: bootcamp/apm/k8s.md
      - Using OpenTelemetry instrumentation: bootcamp/apm/api.md

  - Resources:
    - Cheatsheet: resources/cheatsheet.md
    - Links: resources/index.md
    - FAQ: resources/faq.md
