site_name: 'Splunk App Dev Workshop'
site_description: 'This workshop is going to take you through the exciting journey of App Dev, what this is, why this is important, and how to get started right away!'
site_author: 'Sales Engineering'
site_url: 'https://signalfx.github.io/app-dev-workshop/'
repo_url: 'https://github.com/signalfx/app-dev-workshop/'
edit_uri: ''
copyright: Copyright &copy; 2020 Splunk Inc. All rights reserved.
remote_branch: gh-pages

versions:
  - v1.14
  - v1.13
  - v1.12
  - v1.11
  - v1.10
  - v1.9
  - v1.8
  - v1.7
  - v1.6
  - v1.5
  - v1.4
  - v1.3
  - v1.2

theme:
  name: material
  palette:
    scheme: default
    primary: black
  favicon: images/favicon.ico
  logo: images/logo.png
  font:
    text: Roboto
    code: Ubuntu Mono
  include_search_page: false
  search_index_only: true
  language: en
  custom_dir: docs/material
  features:
    - tabs

markdown_extensions:
  - footnotes
  - admonition
  - attr_list
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.inlinehilite
  - pymdownx.critic
  - pymdownx.keys
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_css:
  - "stylesheets/extra.css"

extra_javascript:
  - "javascripts/extra.js"

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/signalfx/app-dev-workshop
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/splunk
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/splunk/

plugins:
  - git-revision-date-localized:
      type: datetime
      locale: en
  - search
  - minify:
      minify_html: true
      minify_js: true
      htmlmin_opts:
        remove_comments: true
        
nav:
  - 'Home': index.md
  - '<b>SignalFx</b>':
    - '<b>Get Data In</b><br /><small>20 minutes</small>':
      - 'Workshop Introduction': smartagent/intro.md
      - 'Workshop Preparation': smartagent/prep.md
      - 'Deploy the Smart Agent in K3s': smartagent/k3s.md
      - 'Deploy NGINX in K3s' : smartagent/nginx.md
    - '<b>Dashboards</b><br /><small>30 minutes</small>':
      - 'Introduction': dashboards/intro.md
      - 'Editing charts': dashboards/editing.md
      - 'Using filters': dashboards/filtering.md
      - 'Using formulas': dashboards/formulas.md
      - 'Using overlays': dashboards/overlay.md
      - 'SignalFlow': dashboards/signalflow.md
      - 'Adding charts': dashboards/adding-charts.md
    - '<b>Detectors</b><br /><small>15 minutes</small>':
      - 'Creating a Detector': detectors/detectors.md
      - 'Creating a Muting Rule': detectors/muting.md
    - '<b>Monitoring as Code</b><br /><small>10 minutes</small>':
      - 'Using Terraform': mac/terraform.md
    - '<b>µAPM</b><br /><small>25-45 minutes</small>':
      - 'µAPM Architecture Overview': apm/index.md
      - 'Deploying Hot R.O.D. in K3s': apm/hotrod.md
    - '<b>Service Bureau</b><br /><small>20 minutes</small>':
        - 'Billing and Usage' : servicebureau/service_bureau.md
        - 'Teams' : servicebureau/teams.md
    - '<b>Post Workshop Clean Up</b>': module-support/cleanup.md
    - '<b>Optional Modules</b>':
      - 'Deploying Hot R.O.D. in EKS': module-support/hotrod-eks.md
      - 'Deploying Sock Shop in K3s': apm/sockshop.md
      - 'Deploy Smart Agent on a VM': module-support/vm.md
  - '<b>VictorOps</b>':
    - '<b>Getting Started</b><br /><small>30 minutes</small>':
      - 'Initial Setup': victorops/getting_started/index.md
      - 'Create test environment': victorops/getting_started/multipass.md
      - 'Paging polices': victorops/getting_started/paging.md
      - 'Creating a team': victorops/getting_started/team.md
      - 'Configure Rotations': victorops/getting_started/rotations.md
      - 'Configure Escalation Policies': victorops/getting_started/escalation.md
      - 'Creating Routing keys': victorops/getting_started/routing.md
    - '<b>Integrations</b><br /><small>30 minutes</small>': victorops/vo_integrations.md
    - '<b>Incident Lifecycle</b><br /><small>30 minutes</small>':
      - 'Overview': victorops/incident_lifecycle/index.md
      - 'Create incidents': victorops/incident_lifecycle/create_incidents.md
      - 'Manage incidents': victorops/incident_lifecycle/manage_incidents.md
    - '<b>Workshop Clean-up</b><br /><small>2 minutes</small>': victorops/cleanup.md