#cloud-config
ssh_pwauth: yes
password: AppDev2020!
chpasswd:
  expire: false

package_update: true

packages:
  - unzip

runcmd:
# Download Workshop
- export WSVERSION=v1.14
- curl -s -OL https://github.com/signalfx/app-dev-workshop/archive/$WSVERSION.zip
- unzip -qq $WSVERSION.zip -d /home/ubuntu/
- mv /home/ubuntu/app-dev-workshop-${WSVERSION#v} /home/ubuntu/workshop
# Configure motd
- curl -s https://raw.githubusercontent.com/signalfx/app-dev-workshop/master/etc/motd -o /etc/motd
- chmod -x /etc/update-motd.d/*
# Install Terraform
- curl -s -OL https://releases.hashicorp.com/terraform/0.12.25/terraform_0.12.25_linux_amd64.zip
- unzip -qq terraform_0.12.25_linux_amd64.zip -d /usr/local/bin/
# Set correct permissions on ubuntu user home directory
- chown -R ubuntu:ubuntu /home/ubuntu
# Install Smart Agent
- curl -sSL https://dl.signalfx.com/signalfx-agent.sh > /tmp/signalfx-agent.sh
- sh /tmp/signalfx-agent.sh --realm SIGNALFX_REALM -- SIGNALFX_ACCESS_TOKEN