# ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-contrib-configmap
data:
  splunk_trace_url: "https://ingest.[REALM].signalfx.com/v2/trace/otlp"
  splunk_api_url: "https://api.[REALM].signalfx.com"
  splunk_ingest_url: "https://ingest.[REALM].signalfx.com"
  splunk_hec_url: "[URL]:[PORT]/services/collector/event"
  splunk_index: "[INDEX]"
  k8s_cluster_name: "[CLUSTER_NAME]"
  deployment_environment: "[DEPLOYMENT_ENVIRONMENT]"
---
# Secrets
apiVersion: v1
kind: Secret
metadata:
  name: otel-contrib-collector
  namespace: default
  labels:
    app.kubernetes.io/name: otel-collector
    app: otel-collector
type: Opaque
stringData:
  splunk_observability_access_token: [ACCESS_TOKEN]
  splunk_hec_token: [HEC_TOKEN]