# ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-contrib-configmap
data:
  splunk_trace_url: "https://ingest.eu0.signalfx.com/v2/trace/otlp"
  splunk_api_url: "https://api.eu0.signalfx.com"
  splunk_ingest_url: "https://ingest.eu0.signalfx.com"
  splunk_hec_url: "https://http-inputs-o11y-workshop-eu0.splunkcloud.com:443/services/collector/event"
  splunk_index: "splunk4rookies-workshop"
  k8s_cluster_name: "5985-workshop-4898-cluster"
  deployment_environment: "5985-workshop-4898-workshop"
---
# Secrets
apiVersion: v1
kind: Secret
metadata:
  name: otel-contrib-collector
  namespace: default
  labels:
    app.kubernetes.io/name: otel-collector
    app: otel-collector
type: Opaque
stringData:
  splunk_observability_access_token: ***REMOVED***
  splunk_hec_token: ***REMOVED***