#cloud-config
ssh_pwauth: yes
password: Observability2020!
chpasswd:
  expire: false

#package_update: true

apt:
  sources_list: | 
    deb mirror://mirrors.ubuntu.com/mirrors.txt bionic main restricted universe multiverse
    deb mirror://mirrors.ubuntu.com/mirrors.txt bionic-backports main restricted universe multiverse
    deb mirror://mirrors.ubuntu.com/mirrors.txt bionic-updates main restricted universe multiverse
    deb mirror://mirrors.ubuntu.com/mirrors.txt bionic-security main restricted universe multiverse

packages:
  - unzip

write_files:
  - path: /etc/skel/.profile
    content: | 
      echo "Waiting for cloud-init status..."
      if ! /usr/bin/timeout 180 grep -q 'Cloud-init .*finished at' <(tail -f /var/log/cloud-init-output.log); then
        echo "Instance setup did not complete after 3 minutes. Please try again.";
      else
        echo "Your instance is ready!";
      fi 

      if [ -e ~/.instance ]; then
         INSTANCE=$(cat ~/.instance)
      fi
      if [ -z ${INSTANCE+x} ]; then
        if curl -s -m 3 http://169.254.169.254/latest/dynamic/instance-identity/document | grep -q availabilityZone ; then
          # on AWS, grab instance id and use that
          #AWSTOKEN=$(curl -qs -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600")
          #INSTANCE=$(curl -qs -H "X-aws-ec2-metadata-token: $AWSTOKEN" http://169.254.169.254/latest/meta-data/instance-id)
          INSTANCE=$(cat /dev/urandom | base64 | tr -dc 'a-z' | head -c4)-ec2
          # Do two seds to edit the files for persistent hostname change:
          sudo sed -i "s/127.0.0.1.*/127.0.0.1 $INSTANCE.local $INSTANCE localhost/" /etc/hosts
          sudo hostnamectl set-hostname $INSTANCE
          # Set color prompt
          export PS1="${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\$INSTANCE\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ "
        else
          # not AWS, use hostname set via multipass OR create own id here
          # INSTANCE=$(cat /dev/urandom | base64 | tr -dc 'a-z' | head -c4)
          INSTANCE=${HOSTNAME:0:4}
        fi
      echo $INSTANCE > ~/.instance
      fi
      export INSTANCE
    append: true

runcmd:
  # Download Workshop
  - export WSVERSION=5.54
  - 'export WSARCHIVE=$([ "$WSVERSION" = "main" ] && echo "main" || echo "v$WSVERSION")'
  - curl -s -OL https://github.com/splunk/observability-workshop/archive/$WSARCHIVE.zip
  - unzip -qq $WSARCHIVE.zip -d /home/splunk/
  - mv /home/splunk/observability-workshop-$WSVERSION /home/splunk/workshop
  # Configure motd
  - curl -s https://raw.githubusercontent.com/splunk/observability-workshop/main/cloud-init/motd -o /etc/motd
  - chmod -x /etc/update-motd.d/*
  # Install Terraform
  - curl -S -OL https://releases.hashicorp.com/terraform/0.15.0/terraform_0.15.0_linux_amd64.zip
  - unzip -qq terraform_0.15.0_linux_amd64.zip -d /usr/local/bin
  # Set correct permissions on splunk user home directory
  - chown -R splunk:splunk /home/splunk
