#cloud-config
package_update: true
package_upgrade: true

users:
  - default
  - name: splunk
    groups: [docker]
    lock_passwd: true
    sudo: ALL=(ALL) NOPASSWD:ALL

chpasswd:
  expire: false

groups:
  - docker

packages:
  - ansible
  - docker
  - docker-buildx
  - curl
  - docker-compose
  - gnupg2
  - jq
  - maven
  - net-tools
  - openjdk-17-jdk
  - python3-flask
  - python3-venv
  - python3-pip
  - unzip
  - zsh
  - apt-transport-https
  - ca-certificates
  - software-properties-common
  - git
  - wget

write_files:
  - path: /etc/skel/.profile
    append: true
    content: |
      export TERM=xterm-256color
      INSTANCE=$(cat /etc/hostname)
      CLUSTER_NAME="$INSTANCE-cluster"

      export INSTANCE CLUSTER_NAME

      export KUBECONFIG=/home/splunk/.kube/config
      alias kc='kubectl'
      alias dc='docker-compose'

runcmd:
  - chsh -s $(which zsh) splunk
  - su splunk -c 'sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"'
  - echo "source /etc/skel/.profile" >> /home/splunk/.zshrc
  # Install Helm
  - curl -s https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
  # Install K9s (Kubernetes UI)
  - K9S_VERSION=$(curl -s https://api.github.com/repos/derailed/k9s/releases/latest | jq -r '.tag_name')
  - curl -S -OL https://github.com/derailed/k9s/releases/download/"$K9S_VERSION"/k9s_Linux_arm64.tar.gz
  - tar xfz k9s_Linux_arm64.tar.gz -C /usr/local/bin/ k9s
  # Download Workshop
  - curl -s -OL https://github.com/splunk/observability-workshop/archive/main.zip
  - unzip -qq main.zip -d /home/splunk/
  - mkdir /home/splunk/workshop
  - mv /home/splunk/observability-workshop-main/workshop/* /home/splunk/workshop
  - mv /home/splunk/workshop/ansible/diab-v3.yml /home/splunk
  - mv /home/splunk/workshop/ansible/orbstack.yml /home/splunk
  - rm -rf /home/splunk/observability-workshop-main
  - rm -rf /home/splunk/workshop/aws /home/splunk/workshop/cloud-init /home/splunk/workshop/ansible
  - mv /home/splunk/workshop/k3s/demo-in-a-box.zip /home/splunk
  # Download Splunk Observability Content Contrib Repo
  - curl -s -L https://github.com/splunk/observability-content-contrib/archive/main.zip -o content-contrib.zip
  - unzip -qq content-contrib.zip -d /home/splunk/
  - mv /home/splunk/observability-content-contrib-main /home/splunk/observability-content-contrib
  # Install Terraform (latest)
  - TF_VERSION=$(curl -s https://api.github.com/repos/hashicorp/terraform/releases/latest | jq -r '.tag_name | ltrimstr("v")')
  - curl -S -OL https://releases.hashicorp.com/terraform/"$TF_VERSION"/terraform_"$TF_VERSION"_linux_arm64.zip
  - unzip -qq terraform_"$TF_VERSION"_linux_arm64.zip -d /usr/local/bin
  # Install K3s
  - curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE="644" sh -
  # Create kube config and set correct permissions on splunk user home directory
  - mkdir /home/splunk/.kube && kubectl config view --raw > /home/splunk/.kube/config
  - chmod 400 /home/splunk/.kube/config
  - chown -R splunk:splunk /home/splunk
  # Deploy private registry
  - /usr/local/bin/kubectl apply -f /home/splunk/workshop/k3s/registry/registry.yaml
  - sed -i 's/_THEME=\"robbyrussell\"/_THEME=\"gentoo\"/g' home/splunk/.zshrc
  # Chaos Mesh
  - curl -sSL https://mirrors.chaos-mesh.org/v2.6.3/install.sh | bash -s -- --k3s
