name: 0Release new minor version

on: workflow_dispatch

jobs:
  deploy:
    name: Release new minor version
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0
      - uses: ./.github/actions/setup
      - uses: ./.github/actions/deploy
        id: deploy
        with:
          flavour: minor
      - name: Publish release
        uses: softprops/action-gh-release@v1
        with:
          github_token: ${{ github.token }}
          tag_name: ${{ steps.deploy.outputs.tag_name }}
          tag_commitish: refs/tags/${{ steps.deploy.outputs.tag_name }}
